### ISSUE TITLE
[CTD] Crash when creating default world

### ISSUE THREAD

**Issue by drakray** [immortius/chunkbychunk#1]
<details>
<summary>https://pastebin.com/sZ3vkxU8</summary>

```
java.lang.IllegalArgumentException: Multiple entries with same key: com.yungnickyoung.minecraft.betterdungeons.world.structure.[...]
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.yungnickyoung.minecraft.betterdungeons.init.BDModStructureFeatures.addStructureToBiomes(BDModStructureFeatures.java:204) ~[betterdungeons-1.18.1-1.0.1.jar%2379!/:1.18.1-1.0.1] {re:classloading}
	at com.yungnickyoung.minecraft.betterdungeons.init.BDModStructureFeatures.addStructuresToBiomesAndDimensions(BDModStructureFeatures.java:157) ~[betterdungeons-1.18.1-1.0.1.jar%2379!/:1.18.1-1.0.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:395) ~[client-1.18.1-20211210.034407-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:313) ~[client-1.18.1-20211210.034407-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:66) ~[client-1.18.1-20211210.034407-srg.jar%23241!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:644) ~[client-1.18.1-20211210.034407-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```
</details>

Crash to desktop after adding ChunkByChunk to my pack and trying to create a new world

Also, got this https://pastebin.com/AaVJZ9CL after adding CBC when [BuddyCards](https://www.curseforge.com/minecraft/mc-mods/buddycards-expansions/files/3669893) was installed(got an error on load, so I removed it to try CBC, but got the above)

MC 1.18.1
Forge 39.1.2
CBC 1.6.0
Buncha others

**Comment by immortius** [comment]
Thanks for the report - I'll have a look. It certainly seems like an incompatibility with one of the mods on the pack rather, possibly betterdungeons based on the error, so I'll try to work out which one(s) and if I can make changes to accommodate it.

**Comment by immortius** [comment]
This is fixed now in 1.7.0 through a... slightly awkward technique that hopefully won't cause issues with other mods (should be ok).
