### ISSUE TITLE
When trying to set initial_chunks = 0, an error occurs when creating a new world

### ISSUE THREAD

**Issue by dispina** [immortius/chunkbychunk#83]
Hello
I want to make a modpack where the player starts with a full seal world.
But when I set initial_chunks = 0, an error occurs when creating a new world.

Tried both version 1.20.1 and version 1.18.2, same error.

**1.20.1：**
`[21:24:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[guava-31.1-jre.jar:?]
	at xyz.immortius.chunkbychunk.server.ServerEventHandler.spawnInitialChunks(ServerEventHandler.java:388) ~[ChunkByChunk-fabric-1.20.1-2.0.0.jar:?]
	at xyz.immortius.chunkbychunk.server.ServerEventHandler.checkSpawnInitialChunks(ServerEventHandler.java:279) ~[ChunkByChunk-fabric-1.20.1-2.0.0.jar:?]
	at xyz.immortius.chunkbychunk.server.ServerEventHandler.onServerStarted(ServerEventHandler.java:265) ~[ChunkByChunk-fabric-1.20.1-2.0.0.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-d80c247a2af46d5c.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zdi000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2342) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

 **1.18.2：**
`[21:41:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[guava-31.0.1-jre.jar:?]
	at xyz.immortius.chunkbychunk.server.ServerEventHandler.spawnInitialChunks(ServerEventHandler.java:367) ~[ChunkByChunk-fabric-1.18.2-1.13.2.jar:?]
	at xyz.immortius.chunkbychunk.server.ServerEventHandler.checkSpawnInitialChunks(ServerEventHandler.java:263) ~[ChunkByChunk-fabric-1.18.2-1.13.2.jar:?]
	at xyz.immortius.chunkbychunk.server.ServerEventHandler.onServerStarted(ServerEventHandler.java:249) ~[ChunkByChunk-fabric-1.18.2-1.13.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.1.1+cc71601c60-87d8f812a1297025.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zdj000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2812) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

[crash-2023-07-01_21.48.22-server.txt](https://github.com/immortius/chunkbychunk/files/11926124/crash-2023-07-01_21.48.22-server.txt)

**Comment by immortius** [comment]
Addressed in 2.1.0
